- name: Powershell
  hosts: all
  tasks:
     - name: Run basic PowerShell script
       ansible.windows.win_powershell:
         script: |
            $ErrorActionPreference = "continue"
            Write-Output "Hello World!"
            Write-Verbosxe "Hello World!"
            Write-Debug "Hello World!"
