- name: Powershell
  hosts: "{{ server }}"
  tasks:
     - name: Run basic PowerShell script
       ansible.windows.win_powershell:
         script: |
            $value = "{{ foo }}"
            $ErrorActionPreference = "Stop"
            Write-Output "$value"

            EXIT
