- name: Powershell
  hosts: all
  tasks:
     - name: Run basic PowerShell script
       ansible.windows.win_powershell:
         script: |
            $input = $Ansible.ExtraVars.asdf
            $ErrorActionPreference = "Stop"
            Write-Output "$input"
