- name: Powershell
  hosts: all
  vars:
    input_me: value set in playbook var
  tasks:
     - name: Run basic PowerShell script
       ansible.windows.win_powershell:
         script: |
            [CmdLetBinding()]
            param
            (
                [String]$input_me
            )
            $ErrorActionPreference = "Stop"
            Write-Output "$input_me"
