- name: Powershell
  hosts: all
  tasks:
     - name: Run basic PowerShell script
       ansible.windows.win_powershell:
         parameters:
           new_foo: "{{ foo }}"
         script: |
            [CmdLetBinding()]
            param
            (
                [String]$new_foo
            )
            $ErrorActionPreference = "Stop"
            Write-Output $new_foo

