- name: Powershell
  hosts: all
  tasks:
     - name: Run basic PowerShell script
       ansible.windows.win_powershell:
         script: |
            $ErrorActionPreference = "Stop"
            Out-String -InputObject "Hello World!"
