- name: Powershell
  hosts: "{{ server }}"
  tasks:
     - name: Run basic PowerShell script
       ansible.windows.win_powershell:
         parameters:
           value: "{{ foo }}"
         script: |
            [CmdLetBinding()]
            param
            (
                [Parameter(Mandatory = $true)]
                [string]$value
            )
            $ErrorActionPreference = "Stop"
            Write-Output "$value`n"
            
            EXIT
