- name: Powershell
  hosts: all
  vars:
    new_foo: "{{ foo }}"
  tasks:
     - name: Run basic PowerShell script
       ansible.windows.win_powershell:
         script: |
            [CmdLetBinding()]
            param
            (
                [String]$new_foo
            )
            $ErrorActionPreference = "Stop"
            Write-Output $new_foo
