- name: Powershell
  hosts: all
  vars:
    foo: value set in playbook var
  tasks:
     - name: Run basic PowerShell script
       ansible.windows.win_powershell:
         script: |
            [CmdLetBinding()]
            param
            (
                [String]$foo
            )
            $ErrorActionPreference = "Stop"
            Write-Output "The output is: $foo"
