- name: Powershell
  hosts: all
  parameters: foo
  tasks:
     - name: Run basic PowerShell script
       ansible.windows.win_powershell:
         script: |
            [CmdLetBinding()]
            param
            (
                [String]$foo
            )
            $ErrorActionPreference = "Stop"
            Write-Output $foo
