- name: Powershell
  hosts: all
  tasks:
     - name: Run basic PowerShell script
       ansible.windows.win_powershell:
         script: |
            Write-Output "Hello World!"
            Write-Verbose "Hello World!"
            Write-Debug "Hello World!"
