- name: Powershell
  hosts: all

  vars:
    asdf:"this is a test string"
  tasks:
     - name: Run basic PowerShell script
       ansible.windows.win_powershell:
         script: |
            [CmdLetBinding()]
            param
            (
                [String]$asdf
            )
            $ErrorActionPreference = "Stop"
            Write-Output "$asdf"
