- name: Powershell
  hosts: all
  tasks:
     - name: Run basic PowerShell script
       ansible.windows.win_powershell:
         script: |
             [CmdLetBinding()]
            param
            (
                [Parameter(Mandatory = $true)] 
                [String]$input
            )
            $ErrorActionPreference = "Stop"
            Out-String -InputObject "$input"
