- name: Powershell
  hosts: all
  tasks:
     - name: Run basic PowerShell script
       ansible.windows.win_powershell:
       vars:
         foo: this is an input variable
         script: |
            [CmdLetBinding()]
            param
            (
                [String]$foo
            )
            $ErrorActionPreference = "Stop"
            Write-Output "The output is: $foo"
