- name: Powershell
  hosts: all
  tasks:
     - name: Run basic PowerShell script
       ansible.windows.win_powershell:
         script: |
            [CmdLetBinding()]
            param
            (
                [String]$Ansible.foo
            )
            $ErrorActionPreference = "Stop"
            Write-Output $Ansible.foo
