- name: Powershell
  hosts: all
  vars: input
  tasks:
     - name: Run basic PowerShell script
       ansible.windows.win_powershell:
         script: |
            [CmdLetBinding()]
            param
            (
                [String]$input
            )
            $ErrorActionPreference = "Stop"
            Write-Output "$input"
